spring:
  application:
    name: prueba-webflux
  r2dbc:
    url: r2dbc:mysql://localhost:3306/prueba_db
    username: root
    password: 'root'
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  webflux:
    base-path: /prueba

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.r2dbc: INFO
    io.asyncer.r2dbc.mysql: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
